//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zOrder.OMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBarcodeList
    {
        public int Barcode { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public string PName { get; set; }
        public int Operation_Id { get; set; }
        public string OName { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
