//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zOrder.OMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLastTotalOrder
    {
        public long Sira { get; set; }
        public Nullable<int> SipMiktar { get; set; }
        public Nullable<decimal> SipTutar { get; set; }
    }
}
