//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zOrder.OMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrderQYear
    {
        public Nullable<int> Year { get; set; }
        public int Ocak { get; set; }
        public int Subat { get; set; }
        public int Mart { get; set; }
        public int Nisan { get; set; }
        public int Mayis { get; set; }
        public int Haziran { get; set; }
        public int Temmuz { get; set; }
        public int Agustos { get; set; }
        public int Eylul { get; set; }
        public int Ekim { get; set; }
        public int Kasim { get; set; }
        public int Aralik { get; set; }
    }
}
