//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zOrder.OMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class zOrderEntities : DbContext
    {
        public zOrderEntities()
            : base("name=zOrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Mails> Mails { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<vBarcodeList> vBarcodeList { get; set; }
        public virtual DbSet<vCustomers> vCustomers { get; set; }
        public virtual DbSet<vLastTotalOrder> vLastTotalOrder { get; set; }
        public virtual DbSet<vOrderQYear> vOrderQYear { get; set; }
        public virtual DbSet<vOrders> vOrders { get; set; }
        public virtual DbSet<vOrderWYear> vOrderWYear { get; set; }
        public virtual DbSet<vTodayTotalOrder> vTodayTotalOrder { get; set; }
        public virtual DbSet<vTotalOrder> vTotalOrder { get; set; }
    
        public virtual ObjectResult<AylikSiparisTutar_Result> AylikSiparisTutar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AylikSiparisTutar_Result>("AylikSiparisTutar");
        }
    
        public virtual int CalenderCreator(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalenderCreator", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<GetCustomer_Result> GetCustomer(Nullable<int> phoneNumber)
        {
            var phoneNumberParameter = phoneNumber.HasValue ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomer_Result>("GetCustomer", phoneNumberParameter);
        }
    
        public virtual ObjectResult<OrderCalender_Result> OrderCalender(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderCalender_Result>("OrderCalender", dateParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> ToplaTutar(Nullable<System.DateTime> firstodate, Nullable<System.DateTime> lastodate)
        {
            var firstodateParameter = firstodate.HasValue ?
                new ObjectParameter("firstodate", firstodate) :
                new ObjectParameter("firstodate", typeof(System.DateTime));
    
            var lastodateParameter = lastodate.HasValue ?
                new ObjectParameter("lastodate", lastodate) :
                new ObjectParameter("lastodate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("ToplaTutar", firstodateParameter, lastodateParameter);
        }
    }
}
