
name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: test workflow_1
    - name: Run a multi-line script
      run: |
        echo run 1. line,
        echo run 2. line.
